language: c
sudo: false
env:
  global:
  - GIT_EMAIL=poppy-bot-ci@inria.fr
  - GIT_NAME=poppy-bot
  - secure: S2UYRXYZqi7ARBNaPdS8U64sg+c0QR0N6wEZB3ZdKC89MPmjmJTnfLOADm+NX3nswuabueVtxCTLHlGxghg8e4dhVPJiyM3LtliGnW5hYoPGSudzkljli6/gCtutApQzNdspgeWha63O/4nAnUiTGNUwQXVAJw85ZSzKOJ6CaI5K/XqgIN+4RzTO7CKJzK3kj9o+e2cEGcnUfOriF/BjMhN1aujLZ83Sqyb/DQY+17hInaugQvO6AeNvw5Zt4ewykeN9LOTAs9xZwC1sxsrDEZgV87EpFBNH/4pFtPLIwXuiEDAwwmGTjMcUn86y7dgUa/kQUtDNkdoL/gjVivsVTYmmOJlN3l5kmem/URxmRwtPnt2ci4iDNJQokaj0Rb1PMqdAX/6uxjFpneqoALmiDcekPDiWxfcVTke/Cazp08zY3nTGYy7sbIP9+BqnLNIgm4AtGPNfT7RwLkyKUbinVIgy8X7yA0Mgq4S3ru8XiaN7rZ44G4BLuOLCYaRphGr7a/B2kXbFGmnoJCQ0n5svR4Gfe8TQ+0Q2ygaVMxjHUMN/SaSs/nYkx6+DLUnfIqqV5LSpNMdce++wI4dVYtNqrKcXgklvfIAU/tbqgdfNmLiLPK0RXMvtlX1zWEbJny0fZOfPxkn67nIAohTTgT+mZgNyn27sQt672qJleuSsid4=
script:
- git config --global user.email $GIT_EMAIL
- git config --global user.name $GIT_NAME
- set +x
- git_url=https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
- mkdir tmp
- git clone $git_url tmp
- pushd tmp/travis_files
- touch $TRAVIS_COMMIT
- git add -A
- git commit -m "Loop of commits will never end ... $TRAVIS_BUILD_NUMBER"
- git push origin master --force --quiet
- popd
notifications:
  email:
    recipients:
    - theo.segonds@inria.fr
